### PR TITLE
chore: bump version

### PR DESCRIPTION
**Pull request by alexandrius**

### CODE REVIEW

**Comment by mvayngrib** [comment]
@alexandrius what version is this a patch to? 5.0.0-exodus.0?

**Comment by alexandrius** [comment]
@mvayngrib think so, don't remember

**Comment by alexandrius** [comment]
Ah the 5.0.0 was working correctly except the package configuration

**Comment by mvayngrib** [comment]
maybe bump `x` instead in `5.0.0-exodus.x`?

**Comment by alexandrius** [comment]
@mvayngrib Done

**Pull request merged**
